"""multi answer questions

Revision ID: 133a43c8d46b
Revises: 3e01ab4ce887
Created: 2026-09-03 14:19:08.996218+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '133a43c8d46b'
down_revision: str | None = '3e01ab4ce887'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_questions', sa.Column('correct_indexes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'correct_indexes')
    # ### end Alembic commands ###
