"""initial schema

Revision ID: 02051e39d75b
Revises:
Created: 2026-09-02 07:15:03.480584+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = "02051e39d75b"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # Autogenerated from the models, then adjusted to be dialect
    # neutral. See the module docstring.
    op.create_table(
        "audit_entries",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=True),
        sa.Column("actor_id", sa.String(length=36), nullable=True),
        sa.Column("actor_label", sa.String(length=160), nullable=False),
        sa.Column("action", sa.String(length=255), nullable=False),
        sa.Column("target", sa.String(length=255), nullable=True),
        sa.Column("severity", sa.String(length=12), nullable=False),
        sa.Column("cross_tenant", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_audit_entries_org_id"), "audit_entries", ["org_id"], unique=False
    )
    op.create_index(
        "ix_audit_org_created", "audit_entries", ["org_id", "created_at"], unique=False
    )

    op.create_table(
        "organizations",
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("slug", sa.String(length=80), nullable=False),
        sa.Column("package_tier", sa.String(length=16), nullable=False),
        sa.Column("billing_status", sa.String(length=16), nullable=False),
        sa.Column("logo_url", sa.String(length=512), nullable=True),
        sa.Column("logo_text", sa.String(length=60), nullable=True),
        sa.Column("primary_color", sa.String(length=9), nullable=True),
        sa.Column("secondary_color", sa.String(length=9), nullable=True),
        sa.Column("custom_domain", sa.String(length=255), nullable=True),
        sa.Column("student_count", sa.Integer(), nullable=False),
        sa.Column("teacher_count", sa.Integer(), nullable=False),
        sa.Column("grace_period_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_platform", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("org_id"),
        sa.UniqueConstraint("custom_domain"),
    )
    op.create_index(
        op.f("ix_organizations_slug"), "organizations", ["slug"], unique=True
    )

    op.create_table(
        "page_access",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("page_key", sa.String(length=64), nullable=False),
        sa.Column("allowed", sa.Boolean(), nullable=False),
        sa.Column("updated_by", sa.String(length=36), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("org_id", "role", "page_key", name="uq_page_access_scope"),
    )
    op.create_index(
        op.f("ix_page_access_org_id"), "page_access", ["org_id"], unique=False
    )
    op.create_index(
        "ix_page_access_org_role", "page_access", ["org_id", "role"], unique=False
    )

    op.create_table(
        "users",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("user_id"),
        sa.UniqueConstraint("org_id", "email", name="uq_users_org_email"),
    )
    op.create_index(op.f("ix_users_org_id"), "users", ["org_id"], unique=False)
    op.create_index("ix_users_org_role", "users", ["org_id", "role"], unique=False)

    op.create_table(
        "content",
        sa.Column("content_id", sa.String(length=36), nullable=False),
        sa.Column("type", sa.String(length=12), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("subject", sa.String(length=120), nullable=True),
        sa.Column("uploader_id", sa.String(length=36), nullable=True),
        sa.Column("storage_key", sa.String(length=512), nullable=True),
        sa.Column("duration_mins", sa.Integer(), nullable=True),
        sa.Column("size_bytes", sa.Integer(), nullable=True),
        sa.Column("view_count", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["uploader_id"], ["users.user_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("content_id"),
    )
    op.create_index(
        "ix_content_org_created", "content", ["org_id", "created_at"], unique=False
    )
    op.create_index(op.f("ix_content_org_id"), "content", ["org_id"], unique=False)
    op.create_index(
        "ix_content_org_subject", "content", ["org_id", "subject"], unique=False
    )

    op.create_table(
        "events",
        sa.Column("event_id", sa.String(length=36), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("type", sa.String(length=12), nullable=False),
        sa.Column("scheduled_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("duration_mins", sa.Integer(), nullable=False),
        sa.Column("batch", sa.String(length=60), nullable=True),
        sa.Column("created_by", sa.String(length=36), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["created_by"], ["users.user_id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("event_id"),
    )
    op.create_index(op.f("ix_events_org_id"), "events", ["org_id"], unique=False)
    op.create_index(
        "ix_events_org_scheduled", "events", ["org_id", "scheduled_at"], unique=False
    )

    op.create_table(
        "students",
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("batch", sa.String(length=60), nullable=True),
        sa.Column("group", sa.String(length=60), nullable=True),
        sa.Column("parent_id", sa.String(length=36), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["parent_id"], ["users.user_id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["student_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("student_id"),
    )
    op.create_index(
        "ix_students_org_batch", "students", ["org_id", "batch"], unique=False
    )
    op.create_index(op.f("ix_students_org_id"), "students", ["org_id"], unique=False)

    op.create_table(
        "subscriptions",
        sa.Column("subscription_id", sa.String(length=36), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column("stripe_subscription_id", sa.String(length=120), nullable=True),
        sa.Column("stripe_customer_id", sa.String(length=120), nullable=True),
        sa.Column("plan", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=24), nullable=False),
        sa.Column("current_period_end", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["org_id"], ["organizations.org_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("subscription_id"),
        sa.UniqueConstraint("stripe_subscription_id"),
    )
    op.create_index(
        op.f("ix_subscriptions_org_id"), "subscriptions", ["org_id"], unique=False
    )

    op.create_table(
        "teachers",
        sa.Column("teacher_id", sa.String(length=36), nullable=False),
        sa.Column("subjects_taught", sa.Text(), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["teacher_id"], ["users.user_id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("teacher_id"),
    )
    op.create_index(op.f("ix_teachers_org_id"), "teachers", ["org_id"], unique=False)

    op.create_table(
        "class_tickets",
        sa.Column("ticket_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("payment_id", sa.String(length=36), nullable=True),
        sa.Column("signature", sa.String(length=128), nullable=False),
        sa.Column("expiry_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked", sa.Boolean(), nullable=False),
        sa.Column("scan_count", sa.Integer(), nullable=False),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.student_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("ticket_id"),
    )
    op.create_index(
        op.f("ix_class_tickets_org_id"), "class_tickets", ["org_id"], unique=False
    )
    op.create_index(
        "ix_tickets_org_student",
        "class_tickets",
        ["org_id", "student_id"],
        unique=False,
    )

    op.create_table(
        "student_payments",
        sa.Column("payment_id", sa.String(length=36), nullable=False),
        sa.Column("student_id", sa.String(length=36), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("gateway_reference", sa.String(length=160), nullable=True),
        sa.Column("slip_storage_key", sa.String(length=512), nullable=True),
        sa.Column("reviewed_by", sa.String(length=36), nullable=True),
        sa.Column("expiry_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("org_id", sa.String(length=36), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.func.now(),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["student_id"], ["students.student_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("payment_id"),
    )
    op.create_index(
        "ix_payments_org_status", "student_payments", ["org_id", "status"], unique=False
    )
    op.create_index(
        "ix_payments_org_student",
        "student_payments",
        ["org_id", "student_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_student_payments_org_id"), "student_payments", ["org_id"], unique=False
    )


def downgrade() -> None:
    # Autogenerated from the models, then adjusted to be dialect
    # neutral. See the module docstring.
    op.drop_index(op.f("ix_student_payments_org_id"), table_name="student_payments")
    op.drop_index("ix_payments_org_student", table_name="student_payments")
    op.drop_index("ix_payments_org_status", table_name="student_payments")

    op.drop_table("student_payments")
    op.drop_index("ix_tickets_org_student", table_name="class_tickets")
    op.drop_index(op.f("ix_class_tickets_org_id"), table_name="class_tickets")

    op.drop_table("class_tickets")
    op.drop_index(op.f("ix_teachers_org_id"), table_name="teachers")

    op.drop_table("teachers")
    op.drop_index(op.f("ix_subscriptions_org_id"), table_name="subscriptions")

    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_students_org_id"), table_name="students")
    op.drop_index("ix_students_org_batch", table_name="students")

    op.drop_table("students")
    op.drop_index("ix_events_org_scheduled", table_name="events")
    op.drop_index(op.f("ix_events_org_id"), table_name="events")

    op.drop_table("events")
    op.drop_index("ix_content_org_subject", table_name="content")
    op.drop_index(op.f("ix_content_org_id"), table_name="content")
    op.drop_index("ix_content_org_created", table_name="content")

    op.drop_table("content")
    op.drop_index("ix_users_org_role", table_name="users")
    op.drop_index(op.f("ix_users_org_id"), table_name="users")

    op.drop_table("users")
    op.drop_index("ix_page_access_org_role", table_name="page_access")
    op.drop_index(op.f("ix_page_access_org_id"), table_name="page_access")

    op.drop_table("page_access")
    op.drop_index(op.f("ix_organizations_slug"), table_name="organizations")

    op.drop_table("organizations")
    op.drop_index("ix_audit_org_created", table_name="audit_entries")
    op.drop_index(op.f("ix_audit_entries_org_id"), table_name="audit_entries")

    op.drop_table("audit_entries")
