"""learning records: quizzes, attendance, content views

Note the timestamp defaults are sa.func.now(), not sa.text("now()").
Autogenerate rendered the latter because it introspected Postgres, and
now() is Postgres syntax that SQLite cannot parse, so the migration
applied cleanly on the real database and failed on the SQLite the
migration tests use. sa.func.now() compiles per dialect.

Revision ID: 7ec7c316abf6
Revises: 072dea14e14b
Created: 2026-09-03 11:52:52.025996+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7ec7c316abf6'
down_revision: str | None = '072dea14e14b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_records',
    sa.Column('record_id', sa.String(length=36), nullable=False),
    sa.Column('event_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=12), nullable=False),
    sa.Column('marked_by', sa.String(length=36), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.event_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['marked_by'], ['users.user_id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    sa.UniqueConstraint('org_id', 'event_id', 'student_id', name='uq_attendance_once')
    )
    op.create_index('ix_attendance_org_event', 'attendance_records', ['org_id', 'event_id'], unique=False)
    op.create_index('ix_attendance_org_student', 'attendance_records', ['org_id', 'student_id'], unique=False)
    op.create_index(op.f('ix_attendance_records_org_id'), 'attendance_records', ['org_id'], unique=False)
    op.create_table('content_views',
    sa.Column('view_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('viewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('seconds_watched', sa.Integer(), nullable=False),
    sa.Column('progress_pct', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('view_id')
    )
    op.create_index('ix_content_views_org_content', 'content_views', ['org_id', 'content_id'], unique=False)
    op.create_index(op.f('ix_content_views_org_id'), 'content_views', ['org_id'], unique=False)
    op.create_index('ix_content_views_org_student', 'content_views', ['org_id', 'student_id', 'content_id'], unique=False)
    op.create_index('ix_content_views_org_viewed', 'content_views', ['org_id', 'viewed_at'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('attempt_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('student_id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('max_score', sa.Integer(), nullable=False),
    sa.Column('answers', sa.Text(), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('attempt_id')
    )
    op.create_index('ix_quiz_attempts_org_content', 'quiz_attempts', ['org_id', 'content_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_org_id'), 'quiz_attempts', ['org_id'], unique=False)
    op.create_index('ix_quiz_attempts_org_student', 'quiz_attempts', ['org_id', 'student_id'], unique=False)
    op.create_table('quiz_questions',
    sa.Column('question_id', sa.String(length=36), nullable=False),
    sa.Column('content_id', sa.String(length=36), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('options', sa.Text(), nullable=False),
    sa.Column('correct_index', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['content.content_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('question_id')
    )
    op.create_index('ix_quiz_questions_org_content', 'quiz_questions', ['org_id', 'content_id', 'position'], unique=False)
    op.create_index(op.f('ix_quiz_questions_org_id'), 'quiz_questions', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_quiz_questions_org_id'), table_name='quiz_questions')
    op.drop_index('ix_quiz_questions_org_content', table_name='quiz_questions')
    op.drop_table('quiz_questions')
    op.drop_index('ix_quiz_attempts_org_student', table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_org_id'), table_name='quiz_attempts')
    op.drop_index('ix_quiz_attempts_org_content', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index('ix_content_views_org_viewed', table_name='content_views')
    op.drop_index('ix_content_views_org_student', table_name='content_views')
    op.drop_index(op.f('ix_content_views_org_id'), table_name='content_views')
    op.drop_index('ix_content_views_org_content', table_name='content_views')
    op.drop_table('content_views')
    op.drop_index(op.f('ix_attendance_records_org_id'), table_name='attendance_records')
    op.drop_index('ix_attendance_org_student', table_name='attendance_records')
    op.drop_index('ix_attendance_org_event', table_name='attendance_records')
    op.drop_table('attendance_records')
    # ### end Alembic commands ###
