"""content file metadata

Revision ID: 3e01ab4ce887
Revises: 27152aa4011c
Created: 2026-09-03 14:04:08.520945+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3e01ab4ce887'
down_revision: str | None = '27152aa4011c'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('content', sa.Column('original_name', sa.String(length=160), nullable=True))
    op.add_column('content', sa.Column('mime_type', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('content', 'mime_type')
    op.drop_column('content', 'original_name')
    # ### end Alembic commands ###
