"""batches and groups

Revision ID: 27152aa4011c
Revises: 17d6c8a6e41d
Created: 2026-09-03 13:42:00.473556+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '27152aa4011c'
down_revision: str | None = '17d6c8a6e41d'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batches',
    sa.Column('batch_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('groups', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('org_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('batch_id'),
    sa.UniqueConstraint('org_id', 'name', name='uq_batches_org_name')
    )
    op.create_index('ix_batches_org_active', 'batches', ['org_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_batches_org_id'), 'batches', ['org_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batches_org_id'), table_name='batches')
    op.drop_index('ix_batches_org_active', table_name='batches')
    op.drop_table('batches')
    # ### end Alembic commands ###
