"""two factor auth columns

Three nullable columns on users, so this applies to a live table with no
default and no rewrite. Nullable is also the semantics: NULL everywhere
means the account has not enrolled, and only totp_confirmed_at being set
turns the challenge on at login.

add_column with no batch wrapper is correct on both dialects here.
SQLite cannot ALTER a column but it can add one.

Revision ID: 072dea14e14b
Revises: 02051e39d75b
Created: 2026-09-03 11:03:30.390102+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '072dea14e14b'
down_revision: str | None = '02051e39d75b'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('totp_secret', sa.String(length=64), nullable=True))
    op.add_column('users', sa.Column('totp_confirmed_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('recovery_codes', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'recovery_codes')
    op.drop_column('users', 'totp_confirmed_at')
    op.drop_column('users', 'totp_secret')
    # ### end Alembic commands ###
