"""written answers and manual marking

Adds the written question kind and the columns a person needs to mark
one, plus `awarded` on an attempt, which holds marks set by hand for any
question and overrides whatever the server worked out.

Every column is nullable or carries a default, so this applies to a live
table without a rewrite and existing rows keep meaning what they meant:
kind defaults to choice, and an attempt with no awarded marks is scored
exactly as before.

Revision ID: 17d6c8a6e41d
Revises: 7ec7c316abf6
Created: 2026-09-03 12:50:12.812436+00:00

"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '17d6c8a6e41d'
down_revision: str | None = '7ec7c316abf6'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quiz_attempts', sa.Column('marked_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('quiz_attempts', sa.Column('marked_by', sa.String(length=36), nullable=True))
    op.add_column('quiz_attempts', sa.Column('awarded', sa.Text(), nullable=True))
    # Batch mode, because SQLite cannot ALTER a constraint at all and
    # the migration tests run against it. On Postgres batch_alter_table
    # emits the same plain ALTER it would have anyway, so this costs
    # nothing on the dialect that actually ships.
    with op.batch_alter_table('quiz_attempts') as batch:
        batch.create_foreign_key(
            'fk_quiz_attempts_marked_by',
            'users',
            ['marked_by'],
            ['user_id'],
            ondelete='SET NULL',
        )
    # server_default is required, not decoration. The Python side default
    # only fires on an ORM insert, so adding a NOT NULL column to a table
    # that already holds rows fails on the existing ones. It is left in
    # place afterwards rather than dropped, because dropping it needs an
    # ALTER that SQLite cannot do, and a default of "choice" is the right
    # answer for any row that somehow arrives without one.
    op.add_column(
        'quiz_questions',
        sa.Column('kind', sa.String(length=12), nullable=False, server_default='choice'),
    )
    op.add_column('quiz_questions', sa.Column('model_answer', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quiz_questions', 'model_answer')
    op.drop_column('quiz_questions', 'kind')
    with op.batch_alter_table('quiz_attempts') as batch:
        batch.drop_constraint('fk_quiz_attempts_marked_by', type_='foreignkey')
    op.drop_column('quiz_attempts', 'awarded')
    op.drop_column('quiz_attempts', 'marked_by')
    op.drop_column('quiz_attempts', 'marked_at')
    # ### end Alembic commands ###
